### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aertmann** [Flowpack/varnish#12]

**Comment by hlubek** [comment]
- Explain TypoScript cache configuration / dependency
- Show information about https://github.com/FriendsOfSymfony/FOSHttpCache
- Explain backend module
- Write some lines about possible performance improvements (by the user):
  - Ignore tags
  - Tagging of menus
  - "sublayout" issues with DescendantOf_\* (can be resolved in 2.0 with array entry tags)
- Multi-site support
- Shared hosting support
- Content dimensions support

**Comment by aertmann** [comment]
Fixed
