### ISSUE TITLE
Configuration/Settings option to disabled plugin

### ISSUE THREAD

**Issue by ghost** [Flowpack/varnish#29]
Hi,

i would like to have an option to disable the plugin by Settings.yaml configuration, because of our surf deployment script. We use the same composer.json on Development and Production context.

In Development context there is no varnish server available but the plugin causes extreme slow down of all publish actions in neos backend.

At the Production server everything is fine ...

Thanks.

**Comment by aertmann** [comment]
Hi @chrschw,

Thanks for opening an issue. This can be achieved relatively easily and would be a welcomed feature, feel free to push a PR or let me know if you'd be interested in sponsoring the development of it (~1 hour of work).

Suggestion of how to implement it:

- Add `disabled` configuration setting to https://github.com/mocdk/MOC.Varnish/blob/master/Configuration/Settings.yaml with false as default value.
- Inject setting and check in https://github.com/mocdk/MOC.Varnish/blob/master/Classes/MOC/Varnish/Package.php#L16
- Add setting check to these three AOP methods https://github.com/mocdk/MOC.Varnish/blob/master/Classes/MOC/Varnish/Aspects/ContentCacheAspect.php#L31-L73

**Comment by aertmann** [comment]
Solved with #31, tagged `2.2.0` version
