### ISSUE TITLE
CacheTags with Workspace hashes are not supported

### ISSUE THREAD

**Issue by paxuclus** [Flowpack/varnish#41]
In Neos 4.X, cache tags also include a hash of the workspace chain, see https://github.com/neos/neos-development-collection/blob/4.1/Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php#L98

So instead of `NodeType_Neos_Neos-Document`, the nodes are now tagged with
 `NodeType_%d0dbe915091d400bd8ee7f27f0791303%_Neos_Neos-Document`, so pages cached in varnish are currently never banned.

**Comment by aertmann** [comment]
Should be fairly easy to adjust https://github.com/mocdk/MOC.Varnish/blob/master/Classes/Service/ContentCacheFlusherService.php to https://github.com/neos/neos-development-collection/blob/4.0/Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php (https://github.com/neos/neos-development-collection/commit/e5e6ef2130398f98eeb192b8fcc2a30350a38891#diff-e692f71abd5543018b2c17aedd37a6c4)

Just keep in mind that the change was introduced with 4.1, not 4.0 so we'll probably need to branch out 😕 or check if `renderWorkspaceTagForContextNode` exists in the CachingHelper
