### ISSUE TITLE
Neos CMS 5.* version

### ISSUE THREAD

**Issue by sorenmalling** [Flowpack/varnish#48]
Hi,

Any known blockes not mentioned in the issue list in order to release a version for Neos CMS 5.*? :-)

**Comment by hlubek** [comment]
Hi @sorenmalling, I just finished a PR from @daniellienert and released a first alpha for 4.0.0 (https://packagist.org/packages/moc/varnish#4.0.0-alpha1) with Neos 5.* compatibility.

A stable release will follow shortly after we tested this in more Neos installations.
