### ISSUE TITLE
BUG: addFlashMessage can not handle Message object

### ISSUE THREAD

**Issue by sorenmalling** [Flowpack/varnish#50]
When purging content cache for a certain content type (ex. text/css) you will get the following exception after the purging is done

Exception #1243258395 in line 175 of /var/www/website/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/MOC_Varnish_Controller_VarnishCacheController.php: The message body must be of type string, "object" given. - See also: 20200513062504a2ac87.txt

This is due to a Object being passed to the flashMessage.

This change cast it to a string (using the __toString) method of the Message object

**Comment by paxuclus** [comment]
@sorenmalling your patch is included in https://github.com/mocdk/MOC.Varnish/releases/tag/4.0.1
