### ISSUE TITLE
Changing an Asset does not flush pages that reference it

### ISSUE THREAD

**Issue by paxuclus** [Flowpack/varnish#55]
Neos creates the following tags in the content cache when using an asset:
* `AssetDynamicTag_<$workspaceHash>_<assetIdentifier>`
* `AssetDynamicTag_<assetIdentifier>`

Neither of those tags are flushed by this package when an Asset changes (AssetService `assetUpdated` Signal). See the [Neos Package.php](https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Classes/Package.php#L87) for comparison.

Since the `MOC\Varnish\Service\ContentCacheFlusherService` is basically a copy of the Neos `Neos\Neos\Fusion\Cache\ContentCacheFlusher` without the Asset stuff, fixing this is relatively easy, but IMO having that logic duplicated isn't great (that already broke once, see #41 and my guess is it might break again with the event sourced CR).

`Flowpack.FullPageCache` gets around this problem with the following aspect that intercepts the `shutdownObject()` method of the `ContentCacheFlusher` and grabs the cache tags: https://github.com/Flowpack/Flowpack.FullPageCache/blob/master/Classes/Aspects/ContentCacheAspect.php#L44

Since other packages seem to have the same problem, maybe adding a new Signal to the `shutdownObject()` method of the Neos `ContentCacheFlusher` [here](https://github.com/neos/neos-development-collection/blob/205560df9783cccb8562b33d5d977653cdf94122/Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php#L304) is the proper way to resolve this problem.
That way this package could simply connect a Slot to that Signal and flush the same tags that Neos flushes internally.

**Comment by paxuclus** [comment]
@daniellienert what do you think? I would like to add the mentioned Aspect method to a 4.1.1 bugfix release and remove the `ContentCacheFlusherService` completely with 5.0/whichever release is for Neos 7.

**Comment by daniellienert** [comment]
@nlx-lars I agree, thanks for bringing that up. 

I added the 4.0 branch

I just released the 5.0.0 before reading your plan - I thought this was done already and we run that version for some weeks now. But changing such an implementation detail could easily go into a 5.1.0.

**Comment by paxuclus** [comment]
@daniellienert thanks!

#56 can easily go into a 5.1.0 (maybe even 5.1.1), I agree. But dropping the `ContentCacheFlusherService` in between major releases seems wrong. I have actually used that service in client projects to flush varnish pages in custom controllers.

I think we should mark the service as deprecated for now and keep it until the next major. What do you think?
